<?php
session_start(); include 'connect/conn.php';
if(isset($_POST['save_review'])){ if(empty($_SESSION['user'])){header('Location: login.php');exit;} $id=(int)($_POST['review_id']??0);$rating=max(1,min(5,(int)$_POST['rating']));$comment=trim($_POST['comment']);$image=''; if(!empty($_FILES['review_image']['name'])){ $ext=strtolower(pathinfo($_FILES['review_image']['name'],PATHINFO_EXTENSION)); if(in_array($ext,['jpg','jpeg','png','gif','webp'])){$image=time().'_'.rand(100,999).'.'.$ext;move_uploaded_file($_FILES['review_image']['tmp_name'],'img/uploads/'.$image);} } if($id){$stmt=$conn->prepare("UPDATE reviews SET rating=?,comment=?,image=IF(?='',image,?) WHERE review_id=? AND user_id=?");$stmt->bind_param('isssii',$rating,$comment,$image,$image,$id,$_SESSION['user']['user_id']);}else{$stmt=$conn->prepare("INSERT INTO reviews(user_id,rating,comment,image) VALUES(?,?,?,?)");$stmt->bind_param('iiss',$_SESSION['user']['user_id'],$rating,$comment,$image);} $stmt->execute();header('Location: reviews.php');exit;}
if(isset($_GET['delete'])){if(!empty($_SESSION['user'])){$id=(int)$_GET['delete'];$conn->query("DELETE FROM reviews WHERE review_id=$id AND user_id=".(int)$_SESSION['user']['user_id']);}header('Location: reviews.php');exit;}
$pageTitle='รีวิว | Travel Ticket'; include 'header.php'; $edit=null;if(isset($_GET['edit'])&&!empty($_SESSION['user'])){$id=(int)$_GET['edit'];$edit=$conn->query("SELECT * FROM reviews WHERE review_id=$id AND user_id=".(int)$_SESSION['user']['user_id'])->fetch_assoc();}
?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h2 class="section-title mb-1">รีวิวจากผู้เดินทาง</h2><p class="text-muted mb-0">แบ่งปันประสบการณ์และให้คะแนนการจองตั๋ว</p></div><?php if(!empty($_SESSION['user'])):?><a href="#reviewForm" class="btn btn-travel">เขียนรีวิว</a><?php endif;?></div>
<div class="row g-4"><?php $r=$conn->query("SELECT r.*,u.name FROM reviews r JOIN users u ON r.user_id=u.user_id ORDER BY r.review_id DESC");while($v=$r->fetch_assoc()): ?><div class="col-md-6"><div class="page-box h-100"><div class="d-flex justify-content-between"><strong><?=htmlspecialchars($v['name'])?></strong><span class="stars"><?=str_repeat('★',$v['rating']).str_repeat('☆',5-$v['rating'])?></span></div><p class="mt-2 mb-2"><?=nl2br(htmlspecialchars($v['comment']))?></p><?php if($v['image']):?><img src="img/uploads/<?=htmlspecialchars($v['image'])?>" class="review-img"><?php endif;?><?php if(!empty($_SESSION['user'])&&$_SESSION['user']['user_id']==$v['user_id']):?><div class="mt-3"><a href="reviews.php?edit=<?=$v['review_id']?>#reviewForm" class="btn btn-sm btn-outline-travel">แก้ไข</a><a href="reviews.php?delete=<?=$v['review_id']?>" class="btn btn-sm btn-outline-danger ms-1" onclick="return confirm('ลบรีวิวนี้หรือไม่?')">ลบ</a></div><?php endif;?></div></div><?php endwhile;?></div>
<?php if(!empty($_SESSION['user'])): ?><div class="row justify-content-center mt-5" id="reviewForm"><div class="col-lg-7"><div class="page-box"><h4 class="section-title">ให้คะแนน Travel Ticket</h4><form method="post" enctype="multipart/form-data"><input type="hidden" name="review_id" value="<?=$edit['review_id']??0?>"><label class="form-label">คะแนน</label><select name="rating" class="form-select mb-3"><?php for($i=5;$i>=1;$i--):?><option value="<?=$i?>" <?=isset($edit['rating'])&&$edit['rating']==$i?'selected':''?>><?=$i?> ดาว</option><?php endfor;?></select><label class="form-label">ความคิดเห็น</label><textarea name="comment" class="form-control mb-3" rows="4" required><?=htmlspecialchars($edit['comment']??'')?></textarea><label class="form-label">อัปโหลดรูปภาพ</label><input type="file" name="review_image" class="form-control mb-3" accept="image/*"><button name="save_review" class="btn btn-travel"><?= $edit?'บันทึกการแก้ไข':'ส่งรีวิว'?></button></form></div></div></div><?php endif; ?>
<?php include 'footer.php'; ?>
